# Generated by Django 4.1.5 on 2023-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
