# Generated by Django 4.1.5 on 2023-03-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
