# Generated by Django 4.1.5 on 2023-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_listing_year_built'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='lot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
