# Generated by Django 4.1.5 on 2023-03-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_listing_long_listing_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='isActive',
        ),
    ]
